function configure_ppo_simulink_model(mdl,saveChanges)
%CONFIGURE_PPO_SIMULINK_MODEL Configure MEP-PPO interface functions.
arguments
    mdl (1,1) string = "assumed_mode_ppo_simulink"
    saveChanges (1,1) logical = true
end

load_system(mdl);
rt = sfroot;
setChartScript(rt,mdl+"/MATLAB Function", ...
    "function obs = observation_block(x,tau_prev,par)"+newline+ ...
    "%#codegen"+newline+ ...
    "obs = zeros(12,1);"+newline+ ...
    "obs = ppo_observation(x,tau_prev,par);"+newline+ ...
    "end");
setChartScript(rt,mdl+"/MATLAB Function2", ...
    "function reward = reward_block(x,x_prev,tau_applied,tau_applied_prev,done,par)"+newline+ ...
    "%#codegen"+newline+ ...
    "reward = 0.0;"+newline+ ...
    "reward = ppo_reward(x,x_prev,tau_applied,tau_applied_prev,done,par);"+newline+ ...
    "end");
setChartScript(rt,mdl+"/MATLAB Function3", ...
    "function done = done_block(x,par)"+newline+ ...
    "%#codegen"+newline+ ...
    "done = false;"+newline+ ...
    "done = ppo_done(x,par);"+newline+ ...
    "end");

set_param(mdl+"/Unit Delay", ...
    "InitialCondition","tau_prev0","SampleTime","Ts");
set_param(mdl+"/Previous State", ...
    "InitialCondition","x_prev0","SampleTime","Ts");
set_param(mdl+"/Previous Previous Torque", ...
    "InitialCondition","tau_prev0","SampleTime","Ts");

if saveChanges
    save_system(mdl,[],"OverwriteIfChangedOnDisk",true);
end
end

function setChartScript(rt,path,script)
chart = find(rt,"-isa","Stateflow.EMChart","Path",path);
assert(isscalar(chart),"Expected one MATLAB Function chart at %s.",path);
chart.Script = char(script);
end
