function done = ppo_done(x,par)
%PPO_DONE Stop only unsafe or numerically invalid trajectories.
%#codegen

finiteState = true;
for k = 1:6
    finiteState = finiteState && isfinite(x(k));
end

done = ~finiteState ...
    || abs(x(1)-par(19)) > 1.25 ...
    || abs(x(2)) > 6.0 ...
    || abs(x(3)) > 0.08 ...
    || abs(x(4)) > 2.0 ...
    || abs(x(5)) > 0.02 ...
    || abs(x(6)) > 2.0;
end
