clear; clc; close all;
close_stale_rl_models("assumed_mode_ppo_simulink");

%% Plant and direct-torque PPO interface
p = build_assumed_mode_params_actor_critic();
Ts = 0.02;
x0 = zeros(6,1);
x_prev0 = x0;
tau_prev0 = 0.0;
par = build_ppo_parameter_vector(p,Ts,1);

assignin("base","p",p);
assignin("base","par",par);
assignin("base","x0",x0);
assignin("base","x_prev0",x_prev0);
assignin("base","tau_prev0",tau_prev0);
assignin("base","Ts",Ts);

mdl = build_ppo_simulink_model(false);
agentBlk = mdl+"/RL Agent";
configure_ppo_simulink_model(mdl,false);
set_param(mdl, ...
    SolverType="Fixed-step", ...
    Solver="ode4", ...
    FixedStep="0.002", ...
    SimulationMode="normal");

trainingScopes = find_system(mdl,LookUnderMasks="all", ...
    IncludeCommented="on",BlockType="Scope");
for k = 1:numel(trainingScopes)
    set_param(trainingScopes{k},"Commented","on");
end

obsInfo = rlNumericSpec([12 1], ...
    LowerLimit=-5*ones(12,1),UpperLimit=5*ones(12,1));
obsInfo.Name = "observations";
actInfo = rlNumericSpec([1 1], ...
    LowerLimit=-p.rl.tau_max,UpperLimit=p.rl.tau_max);
actInfo.Name = "torque";

%% Agent
% The networks are small, so CPU is normally faster than GPU after
useGPU = false;
rng(0,"twister");
agent = create_mep_ppo_agent(obsInfo,actInfo,Ts,useGPU);
assignin("base","agentObj",agent);

% The block mask evaluates agentObj while the environment is constructed,
% so the compatible 12-observation PPO agent must already exist.
env = rlSimulinkEnv(mdl,agentBlk,obsInfo,actInfo);
env.UseFastRestart = "on";

%% Three-stage curriculum
% Give the precision stages more updates: these stages learn braking and
% residual-vibration suppression after stage 1 has learned the transfer.
stageEpisodes = [100 150 150];
stageDurations = [6 8 8];
stageEntropy = [1e-4 5e-5 0];
trainingStats = cell(3,1);
stageMetrics = cell(3,1);
stageCheckpointResults = cell(3,1);
checkpointDirs = strings(3,1);

runTag = string(datetime("now",Format="yyyyMMdd_HHmmss"));
for stage = 1:3
    Tf = stageDurations(stage);
    maxSteps = ceil(Tf/Ts);
    par = build_ppo_parameter_vector(p,Ts,stage);
    assignin("base","par",par);
    assignin("base","Tf",Tf);
    set_param(mdl,"StopTime",num2str(Tf));

    env.ResetFcn = @(simIn) ...
        reset_ppo_flexible_manipulator(simIn,par,stage);
    agent.AgentOptions.EntropyLossWeight = stageEntropy(stage);

    checkpointDirs(stage) = ...
        "savedAgents_mep_ppo_v2_"+runTag+"_stage"+stage;
    trainOpts = rlTrainingOptions( ...
        MaxEpisodes=stageEpisodes(stage), ...
        MaxStepsPerEpisode=maxSteps, ...
        ScoreAveragingWindowLength=20, ...
        StopTrainingCriteria="EpisodeCount", ...
        StopTrainingValue=stageEpisodes(stage), ...
        SaveAgentCriteria="EpisodeFrequency", ...
        SaveAgentValue=10, ...
        SaveAgentDirectory=checkpointDirs(stage), ...
        Plots="training-progress", ...
        Verbose=true);

    evaluator = rlEvaluator( ...
        NumEpisodes=2, ...
        EvaluationFrequency=10, ...
        MaxStepsPerEpisode=maxSteps, ...
        UseExplorationPolicy=false, ...
        RandomSeeds=[11 22]);

    fprintf("\nStarting MEP-PPO curriculum stage %d of 3.\n",stage);
    trainingStats{stage} = train( ...
        agent,env,trainOpts,Evaluator=evaluator);

    % Select by a deterministic physical score, not the last episode or
    % exploratory training reward.
    env.ResetFcn = @(simIn) ...
        reset_ppo_evaluation(simIn,par,pi/6,zeros(6,1));
    [agent,stageMetrics{stage},stageCheckpointResults{stage}] = ...
        ppo_select_best_checkpoint( ...
        checkpointDirs(stage),env,maxSteps,par,pi/6,agent,stage);
    assignin("base","agentObj",agent);

    fprintf( ...
        "Stage %d selected score %.4f, return %.3f, "+ ...
        "final tip error %.3f deg.\n", ...
        stage,stageMetrics{stage}.Score, ...
        stageMetrics{stage}.TotalReward, ...
        rad2deg(stageMetrics{stage}.FinalGammaErrorRad));

    [stagePassed,stageReason] = ...
        ppo_stage_passed(stageMetrics{stage},stage);
    save("ppo_resume_state.mat", ...
        "agent","trainingStats","stageMetrics", ...
        "stageCheckpointResults","checkpointDirs", ...
        "p","par","x0","x_prev0","tau_prev0","Ts","Tf","stage", ...
        "stagePassed","stageReason", ...
        "-v7.3");
    assert(stagePassed, ...
        "Curriculum stopped instead of advancing a failed policy. %s", ...
        stageReason);
end

%% Ten-second publication test
Tf = 10;
maxSteps = ceil(Tf/Ts);
par = build_ppo_parameter_vector(p,Ts,2);
assignin("base","par",par);
assignin("base","Tf",Tf);
assignin("base","agentObj",agent);
set_param(mdl,"StopTime",num2str(Tf));
env.ResetFcn = @(simIn) ...
    reset_ppo_evaluation(simIn,par,pi/6,zeros(6,1));
finalMetrics = ppo_evaluate_agent(agent,env,maxSteps,par,pi/6);

save("ppo_resume_state.mat", ...
    "agent","trainingStats","stageMetrics","finalMetrics", ...
    "stageCheckpointResults","checkpointDirs", ...
    "p","par","x0","x_prev0","tau_prev0","Ts","Tf","-v7.3");

fprintf("Final deterministic MEP-PPO return: %.3f\n", ...
    finalMetrics.TotalReward);
fprintf("Final tip error: %.3f deg; overshoot: %.3f deg.\n", ...
    rad2deg(finalMetrics.FinalGammaErrorRad), ...
    rad2deg(finalMetrics.OvershootRad));

assert(finalMetrics.PassedNominalTracking, ...
    "Final policy failed nominal publication gates; resume state was saved.");
save("trained_mep_ppo.mat", ...
    "agent","trainingStats","stageMetrics","finalMetrics", ...
    "stageCheckpointResults","checkpointDirs", ...
    "p","par","x0","x_prev0","tau_prev0","Ts","Tf");
disp("Published trained_mep_ppo.mat.");
